### ISSUE TITLE
Recommending a reference paper

### ISSUE THREAD

**Issue by liuzyzju** [liudakl/ParAIsite#1]
Hi there,

This is a very interesting research project and the codes are very well organized.  
I read through the arxiv manuscript and would like to recommend some reference paper for further aspect. For example,  in manuscript 'Leveraging low-fidelity data to improve machine learning of sparse high-fidelity thermal conductivity data via transfer learning' (Materials Today Physics 28, 100868 2022) They authors applied the transfer learning approach to enhance thermal conductivity predictions on small dataset via a larger low fidelity AFLOW AGL dataset. I think that paper focused on something directly related to this project and I would like to recommend you guys to cite that paper somewhere.

Great work!

**Comment by liudmylaklochko** [comment]
Hi,
Thank you for reaching out to us regarding the reference.
The paper is well-written, and we will consider integrating it in future peer-review iterations.
Best regards,
LK
